let ELEMENTS = {};

export default ELEMENTS = {
    MAIN: document.querySelector(".main"),
    HEADERS: document.querySelector(".note-headers"),
    MENU_HEADER: document.querySelector(".menu_header"),
    HEADER_SETTINGS: document.querySelector(".add-header-screen"),
    VISUAL_SETTINGS: document.querySelector('.visual-settings-screen'),
    NOTE_SETTINGS: document.querySelector(".note-settings-screen"),
    EXAMPLE: document.querySelector(".example"),
    EXAMPLE_HEAD: document.querySelector(".example_head"),
    EXAMPLE_TXT: document.querySelector(".example_txt"),
    OPTION_HEADER: document.querySelector(".add-header-screen_input"),
    OPTION_URL: document.querySelector(".option_backGround-url"),
    OPTION_HEAD: document.querySelector(".option_header-txt"),
    OPTION_HEAD_FS: document.querySelector(".option_header-font-size"),
    OPTION_TXT: document.querySelector(".option_description-txt"),
    OPTION_TXT_FS: document.querySelector(".option_description-font-size"),
    OPTION_TXT_COLOR: document.querySelector(".option_txt-color"),
    OPTION_MAIN_HEADER: document.querySelector(".option_header-txt-main"),
    OPTION_MAIN_HEADER_FONT_SIZE: document.querySelector(".option_header-font-size-main"),
    OPTION_MAIN_TEXT_FONT_SIZE: document.querySelector(".option_txt-font-size-main"),
    OPTION_MAIN_BASE_COLOR: document.querySelector(".option_base-color-main"),
    OPTION_MAIN_TXT_COLOR: document.querySelector(".option_txt-color-main"),
    OPTION_MAIN_SECOND_BASE_COLOR: document.querySelector(".option_second-base-color"),
    OPTION_MAIN_BUTTON_COLOR: document.querySelector(".option_button-color-main"),
    BUTTON_SUBMIT: document.querySelector(".note_submit"),
    BUTTON_SUBMIT_VISUAL_SETTINGS: document.querySelector(".visual-settings_submit"),
    BUTTON_RESET_NOTE: document.querySelector(".note_exit"),
    BUTTON_CREATE_EXAMPLE: document.querySelector(".note_create-example"),
    BUTTON_ADD_HEADER: document.querySelector(".menu_add-note-header"),
    BUTTON_RESET_HEADER: document.querySelector(".add-header-screen_exit"),
    BUTTON_RESET_VISUAL_SETTINGS : document.querySelector(".visual-settings_exit"),
    BUTTON_SHORTCUTS_SETTINGS: document.querySelector('.settings__shortcuts'),
    BUTTON_TECHNICAL_SETTINGS: document.querySelector('.settings__technical'),
    BUTTON_VISUAL_SETTINGS: document.querySelector('.settings__visual'),
    BUTTON_SUBMIT_HEADER_CREATE: document.querySelector(".add-header-screen_submit"),
    BUTTON_ADD_NOTE: document.querySelectorAll(".note-header_note-add"),
    SETTINGS_ICON: document.querySelector('.setting-icon'),
    SETTINGS: document.querySelector('.settings'),
    LOADER: document.querySelector('.loaders-screen')
};